apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: example-velero
spec:
  olm_managed: false
  default_velero_plugins:
  - aws
  - openshift
  backup_storage_locations:
  - name: default
    provider: aws
    object_storage:
      bucket: velero
    config:
      region: minio
      profile: "default"
      s3_force_path_style: true
      s3_url: "http://9.30.250.138:9000"
    credentials_secret_ref:
      name: my-oadp-secret
      namespace: oadp-operator
  volume_snapshot_locations:
  - name: default
    provider: aws
    config:
      region: minio
      profile: "default"
  enable_restic: true
  use_upstream_images: false
