apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero-sample
spec:
  # Add fields here
  olmManaged: false
  backupStorageLocations:
  - provider: aws
    default: true
    objectStorage:
      bucket: my-minio-bucket
      prefix: 'velero'
    config:
      region: minio
      profile: "default"
      s_3_force_path_style: 'true'
      s_3_url: "http://9.30.250.138:9000"
    credential:
      name: cloud-credentials
      key: cloud
  enable_restic: true
  defaultVeleroPlugins:
  - openshift
  - aws
